version: '3.9'

services:
  postgres:
    container_name: database
    build: ./postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music-link
      POSTGRES_HOST: postgres

